added default headers to constants
supabase-community/realtime-py pull request #16
Opened 2021-08-25 20:36 UTC by doubledare704

passing new parameter to Socket init
converting dict of headers into Headers object while connecting to ws with old client in websockets.

## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Socket class connects with default headers

## What is the new behavior?

Adding custom headers into _connect method as new optional parameter in class

## Additional context

Issue from [link](https://github.com/supabase/realtime-py/issues/15)

2021-10-01 17:44 UTC, awalias requested changes

2021-10-01 17:44 UTC, awalias commented on realtime_py/constants.py
> +    "X-Client-Info": f"gotrue-py/{__version__}"
I think this needs to be `realtime-py`

2021-10-01 17:44 UTC, awalias commented on realtime_py/version.py
> +__version__ = "0.1.0"
is this one static or does it get overwritten dynamically anywhere?

2021-10-01 17:45 UTC, awalias commented
thanks for picking this one up btw @doubledare704 ! I actually forgot that we can't send headers via the ws connection

2021-11-18 13:02 UTC, dreinon commented
@awalias then should we close this PR?

2022-01-17 06:37 UTC, J0 commented
Hey @doubledare704,

Thanks for your contribution! Unfortunately, it seems like we have to close this for now since we can't send headers over websockets. We really appreciate the time and effort put into this PR though! We can close this for now if we find a workaround.

 If you'd like some stickers do feel free to reach out to me on Discord(J0).

@dreinon @awalias feel free to chime in if you have any concerns/thoughts as well.

Thanks!
Joel

2022-01-17 06:37 UTC, closed without merging